# Generated by Django 4.1.5 on 2023-01-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYUpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jungbo',
            name='content',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
