# Generated by Django 4.1.5 on 2023-01-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYUpage', '0002_alter_jungbo_content_alter_jungbo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jungbo',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
