# Generated by Django 4.1.5 on 2023-02-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYUpage', '0002_alter_jungbo_grade_alter_jungbo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jungbo',
            name='cooperation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='jungbo',
            name='spend_time',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jungbo',
            name='track',
            field=models.TextField(default=''),
        ),
    ]
