# Generated by Django 4.1.5 on 2023-02-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYUpage', '0004_alter_jungbo_cooperation_alter_jungbo_spend_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jungbo',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='Department',
            field=models.CharField(default='Department', max_length=50),
        ),
    ]
