# Generated by Django 4.1.5 on 2023-02-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYUpage', '0005_jungbo_github_alter_jungbo_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='jungbo',
            name='in_university',
            field=models.CharField(choices=[('재학', '재학'), ('휴학', '휴학')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='jungbo',
            name='my_track',
            field=models.CharField(choices=[('기획/디자인', '기획/디자인'), ('프론트엔드', '프론트엔드'), ('백엔드', '백엔드')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='jungbo',
            name='notebook',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='jungbo',
            name='session',
            field=models.CharField(choices=[('참석', '참석'), ('불참', '불참')], default='', max_length=5),
        ),
    ]
