# Generated by Django 4.1.5 on 2023-02-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYUpage', '0006_jungbo_in_university_jungbo_my_track_jungbo_notebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jungbo',
            name='in_university',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='my_track',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='notebook',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='session',
            field=models.CharField(default='', max_length=5),
        ),
    ]
