# Generated by Django 4.1.5 on 2023-02-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYUpage', '0007_alter_jungbo_in_university_alter_jungbo_my_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jungbo',
            name='Department',
            field=models.CharField(default='Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='grade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='in_university',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='my_track',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='notebook',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jungbo',
            name='session',
            field=models.CharField(default='', max_length=100),
        ),
    ]
