# Generated by Django 4.1.5 on 2023-01-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_qcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcomment',
            name='quest',
        ),
        migrations.AddField(
            model_name='qcomment',
            name='quest_id',
            field=models.ForeignKey(db_column='qid', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='qcomment', to='question.quest'),
            preserve_default=False,
        ),
    ]
