# Generated by Django 4.1.5 on 2023-01-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_qcomment_quest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='quser',
            new_name='user',
        ),
    ]
